CREATE TABLE IF NOT EXISTS LEILAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR,
    ENCERRADO BOOLEAN,
    DATA DATE
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR,
    EMAIL VARCHAR
);